controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_user:
    path: '/user'
    controller: 'App\Controller\UserController::add'
    methods: POST

get_all_users:
    path: '/users'
    controller: 'App\Controller\UserController::getAll'
    methods: GET

get_user:
    path: '/user/{id}'
    controller: 'App\Controller\UserController::get'
    methods: GET

update_user:
    path: '/user/{id}'
    controller: 'App\Controller\UserController::update'
    methods: PUT

delete_user:
    path: '/user/{id}'
    controller: 'App\Controller\UserController::delete'
    methods: DELETE

add_car:
    path: '/car'
    controller: 'App\Controller\CarController::add'
    methods: POST

get_all_cars:
    path: '/car'
    controller: 'App\Controller\CarController::getAll'
    methods: GET

get_car:
    path: '/car/{id}'
    controller: 'App\Controller\CarController::get'
    methods: GET

update_car:
    path: '/car/{id}'
    controller: 'App\Controller\CarController::update'
    methods: PUT

delete_car:
    path: '/car/{id}'
    controller: 'App\Controller\CarController::delete'
    methods: DELETE

add_rent:
    path: '/rent'
    controller: 'App\Controller\RentController::add'
    methods: POST