controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_user:
    path: '/user/add'
    controller: 'App\Controller\UserController::add'
    methods: POST

get_all_users:
    path: '/users/getAll'
    controller: 'App\Controller\UserController::getAll'
    methods: GET

get_user:
    path: '/users/get/{id}'
    controller: 'App\Controller\UserController::get'
    methods: GET

update_user:
    path: '/user/update/{id}'
    controller: 'App\Controller\UserController::update'
    methods: PUT

delete_user:
    path: '/user/delete/{id}'
    controller: 'App\Controller\UserController::delete'
    methods: DELETE