controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_user:
    path: '/user/add'
    controller: 'App\Controller\UserController::add'
    methods: POST